CREATE DATABASE IF NOT EXISTS `ad_tema6`;
USE `ad_tema6`;

CREATE TABLE IF NOT EXISTS `deportistas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(40) COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `activo` tinyint(1) NOT NULL DEFAULT '0',
  `genero` enum('Masculino','Femenino') COLLATE utf8_spanish_ci NOT NULL,
  `deporte` varchar(40) COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

INSERT INTO `deportistas` (`id`, `nombre`, `activo`, `genero`, `deporte`) VALUES
	(1, 'Alex Criville', 0, 'Masculino', 'Motociclismo'),
	(2, 'Alexander Popov', 0, 'Masculino', 'Natación'),
	(3, 'Alfredo Di Stefano', 0, 'Masculino', 'Futbol'),
	(4, 'Almudena Cid', 0, 'Femenino', 'Gimnasia Rítmica'),
	(5, 'Amaya Valdemoro', 0, 'Femenino', 'Baloncesto'),
	(6, 'Ana Ivanovic', 1, 'Femenino', 'Tenis'),
	(7, 'Anatoli Karpov', 0, 'Masculino', 'Ajedrez'),
	(8, 'Angel Nieto', 0, 'Masculino', 'Motociclismo'),
	(9, 'Anna Kournikova', 0, 'Femenino', 'Tenis'),
	(10, 'Arantxa Sánchez Vicario', 0, 'Femenino', 'Tenis'),
	(11, 'Bjorn Borg', 0, 'Masculino', 'Tenis'),
	(12, 'Blanca Fernández Ochoa', 0, 'Femenino', 'Esquí'),
	(13, 'Bob Beamon', 0, 'Masculino', 'Atletismo'),
	(14, 'Bobby Fischer', 0, 'Masculino', 'Ajedrez'),
	(15, 'Carl Lewis', 0, 'Masculino', 'Atletismo'),
	(16, 'Carlos Sainz', 1, 'Masculino', 'Automovilismo'),
	(17, 'Carmelo Anthony', 1, 'Masculino', 'Baloncesto'),
	(18, 'Caroline Wozniacki', 1, 'Femenino', 'Tenis'),
	(19, 'Conchita Martínez', 0, 'Femenino', 'Tenis'),
	(20, 'Coral Bistuer', 0, 'Femenino', 'Taekwondo'),
	(21, 'Cristiano Ronaldo', 1, 'Masculino', 'Fútbol'),
	(22, 'Dani Pedrosa', 1, 'Masculino', 'Motociclismo'),
	(23, 'Danica Patrick', 1, 'Femenino', 'Automovilismo'),
	(24, 'Dirk Nowitzki', 1, 'Masculino', 'Baloncesto'),
	(25, 'Dwyane Wade', 1, 'Masculino', 'Baloncesto'),
	(26, 'Eddy Merckx', 0, 'Masculino', 'Ciclismo'),
	(27, 'Edurne Pasaban', 1, 'Femenino', 'Montañismo'),
	(28, 'Emil Zatopek', 0, 'Masculino', 'Atletismo'),
	(29, 'Emilio Butrageño', 0, 'Masculino', 'Fútbol'),
	(30, 'Epi', 0, 'Masculino', 'Baloncesto'),
	(31, 'Evander Holyfield', 0, 'Masculino', 'Boxeo'),
	(32, 'Fernado Alonso', 1, 'Masculino', 'Automovilismo'),
	(33, 'Fernando Romay', 0, 'Masculino', 'Baloncesto'),
	(34, 'Fernando Torres', 1, 'Masculino', 'Fútbol'),
	(35, 'Florence Griffith', 0, 'Femenino', 'Atletismo'),
	(36, 'Floyd Mayweather', 1, 'Masculino', 'Boxeo'),
	(37, 'Franz Beckenbauer', 0, 'Masculino', 'Fútbol'),
	(38, 'Garrincha', 0, 'Masculino', 'Fútbol'),
	(39, 'Gary Kasparov', 0, 'Masculino', 'Ajedrez'),
	(40, 'Gemma Mengual', 0, 'Femenino', 'Natación Sincronizada'),
	(41, 'George Forerman', 0, 'Masculino', 'Boxeo'),
	(42, 'Giacomo Agostini', 0, 'Masculino', 'Motociclismo'),
	(43, 'Gisela Pulido', 1, 'Masculino', 'Kitesurf'),
	(44, 'Ian Thorpe', 0, 'Masculino', 'Natacion'),
	(45, 'Javier Sotomayor', 0, 'Masculino', 'Atletismo'),
	(46, 'Jenson Button', 1, 'Masculino', 'Automovilismo'),
	(47, 'Jesse Owens', 0, 'Masculino', 'Atletismo'),
	(48, 'Joe Di Maggio', 0, 'Masculino', 'Beisbol'),
	(49, 'Joe Frazier', 0, 'Masculino', 'Boxeo'),
	(50, 'Joe Montana', 0, 'Masculino', 'Fútbol Americano'),
	(51, 'Johan Cruyff', 0, 'Masculino', 'Fútbol'),
	(52, 'Jorge Lorenzo', 1, 'Masculino', 'Motociclismo'),
	(53, 'Jose Raul Capablanca', 0, 'Masculino', 'Ajedrez'),
	(54, 'Juan Carlos Navarro', 1, 'Masculino', 'Baloncesto'),
	(55, 'Juan Manuel Fangio', 0, 'Masculino', 'Automovilismo'),
	(56, 'Jutta Kleinsmith', 0, 'Femenino', 'Atuomovilismo'),
	(57, 'Kareem Abdul Jabbar', 0, 'Masculino', 'Baloncesto'),
	(58, 'Karl Malone', 0, 'Masculino', 'Baloncesto'),
	(59, 'Kobe Bryant', 1, 'Masculino', 'Baloncesto'),
	(60, 'Lance Armstrong', 0, 'Masculino', 'Ciclismo'),
	(61, 'Larry Bird', 0, 'Masculino', 'Baloncesto'),
	(62, 'Lebron James', 1, 'Masculino', 'Baloncesto'),
	(63, 'Lev Yashin', 0, 'Masculino', 'Fútbol'),
	(64, 'Lionel Messi', 1, 'Masculino', 'Fútbol'),
	(65, 'Lothar Matthaus', 0, 'Masculino', 'Fútbol'),
	(66, 'Magic Johnson', 0, 'Masculino', 'Baloncesto'),
	(67, 'Manny Pacquiao', 1, 'Masculino', 'Boxeo'),
	(68, 'María De Villota', 0, 'Femenino', 'Automovilismo'),
	(69, 'Maradona', 0, 'Masculino', 'Fútbol'),
	(70, 'Marc Marquez', 1, 'Masculino', 'Motociclismo'),
	(71, 'Maria Sharapova', 1, 'Femenino', 'Tenis'),
	(72, 'Mark Spitz', 0, 'Masculino', 'Natacion'),
	(73, 'Marta Domínguez', 0, 'Femenino', 'Atletismo'),
	(74, 'Michael Johnson', 0, 'Masculino', 'Atletismo'),
	(75, 'Michael Jordan', 0, 'Masculino', 'Baloncesto'),
	(76, 'Michael Phelps', 0, 'Masculino', 'Natacion'),
	(77, 'Michael Schumacher', 0, 'Masculino', 'Automovilismo'),
	(78, 'Michel Platini', 0, 'Masculino', 'Fútbol'),
	(79, 'Miguel Indurain', 0, 'Masculino', 'Ciclismo'),
	(80, 'Mike Doohan', 0, 'Masculino', 'Motociclismo'),
	(81, 'Mike Tyson', 0, 'Masculino', 'Boxeo'),
	(82, 'Mireia Belmonte', 1, 'Femenino', 'Natación'),
	(83, 'Muhammad Ali', 0, 'Masculino', 'Boxeo'),
	(84, 'Nadia Comaneci', 0, 'Femenino', 'Gimnasia'),
	(85, 'Nani Roma', 0, 'Masculino', 'Motociclismo'),
	(86, 'Nani Roma', 1, 'Masculino', 'Automovilismo'),
	(87, 'Paul Gasol', 1, 'Masculino', 'Baloncesto'),
	(88, 'Pelé', 0, 'Masculino', 'Fútbol'),
	(89, 'Pete Sampras', 0, 'Masculino', 'Tenis'),
	(90, 'Peyton Manning', 1, 'Masculino', 'Fútbol Americano'),
	(91, 'Rafa Nadal', 1, 'Masculino', 'Tenis'),
	(92, 'Rocky Marciano', 0, 'Masculino', 'Boxeo'),
	(93, 'Roger Federer', 1, 'Masculino', 'Tenis'),
	(94, 'Ronaldinho', 0, 'Masculino', 'Fútbol'),
	(95, 'Ronaldo', 0, 'Masculino', 'Fútbol'),
	(96, 'Scottie Pippen', 0, 'Masculino', 'Baloncesto'),
	(97, 'Sebastien Loeb', 1, 'Masculino', 'Automovilismo'),
	(98, 'Serena Williams', 1, 'Femenino', 'Tenis'),
	(99, 'Sergei Bubka', 0, 'Masculino', 'Atletismo'),
	(100, 'Sete Gibernau', 0, 'Masculino', 'Motociclismo'),
	(101, 'Severiano Ballesteros', 0, 'Masculino', 'Golf'),
	(102, 'Shaquille O´Neill', 0, 'Masculino', 'Baloncesto'),
	(103, 'Sheila Herrero', 1, 'Femenino', 'Patinaje'),
	(104, 'Sugar Ray Robinson', 0, 'Masculino', 'Boxeo'),
	(105, 'Talant Dujshebaev', 0, 'Masculino', 'Balomano'),
	(106, 'Theresa Zabell', 0, 'Femenino', 'Vela'),
	(107, 'Tiger Woods', 1, 'Masculino', 'Golf'),
	(108, 'Tony Hawk', 0, 'Masculino', 'Skateboard'),
	(109, 'Usain Bolt', 1, 'Masculino', 'Atletismo'),
	(110, 'Valentino Rossi', 1, 'Masculino', 'Motociclismo'),
	(111, 'Wayne Rainey', 0, 'Masculino', 'Motociclismo'),
	(112, 'Wayne Rooney', 1, 'Masculino', 'Fútbol'),
	(113, 'Yelena Isinbayeva', 0, 'Femenino', 'Atletismo'),
	(114, 'Zinedine Zidane', 0, 'Masculino', 'Fútbol');

CREATE TABLE IF NOT EXISTS `imagenes` (
  `id` int(11) DEFAULT NULL,
  `nombre` varchar(40) DEFAULT NULL,
  `path` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `imagenes` (`id`, `nombre`, `path`) VALUES
	(100, '100_1_Sete_Gibernau.jpg', './imagenes'),
	(100, '100_2_Sete_Gibernau.jpg', './imagenes'),
	(100, '100_3_Sete_Gibernau.jpg', './imagenes'),
	(100, '100_4_Sete_Gibernau.jpg', './imagenes'),
	(100, '100_5_Sete_Gibernau.jpg', './imagenes'),
	(101, '101_1_Severiano_Ballesteros.jpg', './imagenes'),
	(101, '101_2_Severiano_Ballesteros.jpg', './imagenes'),
	(101, '101_3_Severiano_Ballesteros.jpg', './imagenes'),
	(101, '101_4_Severiano_Ballesteros.jpg', './imagenes'),
	(101, '101_5_Severiano_Ballesteros.jpg', './imagenes'),
	(102, '102_1_Shaquille_O´Neill.jpg', './imagenes'),
	(102, '102_2_Shaquille_O´Neill.jpg', './imagenes'),
	(102, '102_3_Shaquille_O´Neill.jpg', './imagenes'),
	(102, '102_4_Shaquille_O´Neill.jpg', './imagenes'),
	(102, '102_5_Shaquille_O´Neill.jpg', './imagenes'),
	(102, '102_6_Shaquille_O´Neill.jpg', './imagenes'),
	(102, '102_7_Shaquille_O´Neill.jpg', './imagenes'),
	(102, '102_8_Shaquille_O´Neill.jpg', './imagenes'),
	(103, '103_1_Sheila_Herrero.jpg', './imagenes'),
	(103, '103_2_Sheila_Herrero.jpg', './imagenes'),
	(103, '103_3_Sheila_Herrero.jpg', './imagenes'),
	(103, '103_4_Sheila_Herrero.jpg', './imagenes'),
	(103, '103_5_Sheila_Herrero.jpg', './imagenes'),
	(103, '103_6_Sheila_Herrero.jpg', './imagenes'),
	(103, '103_7_Sheila_Herrero.jpg', './imagenes'),
	(104, '104_1_Sugar_Ray_Robinson.jpg', './imagenes'),
	(104, '104_2_Sugar_Ray_Robinson.jpg', './imagenes'),
	(104, '104_3_Sugar_Ray_Robinson.jpg', './imagenes'),
	(104, '104_4_Sugar_Ray_Robinson.jpg', './imagenes'),
	(104, '104_5_Sugar_Ray_Robinson.jpg', './imagenes'),
	(104, '104_6_Sugar_Ray_Robinson.jpg', './imagenes'),
	(104, '104_7_Sugar_Ray_Robinson.jpg', './imagenes'),
	(105, '105_1_Talant_Dujshebaev.jpg', './imagenes'),
	(105, '105_2_Talant_Dujshebaev.jpg', './imagenes'),
	(105, '105_3_Talant_Dujshebaev.jpg', './imagenes'),
	(105, '105_4_Talant_Dujshebaev.jpg', './imagenes'),
	(105, '105_5_Talant_Dujshebaev.jpg', './imagenes'),
	(105, '105_6_Talant_Dujshebaev.jpg', './imagenes'),
	(106, '106_1_Theresa_Zabell.jpg', './imagenes'),
	(106, '106_2_Theresa_Zabell.jpg', './imagenes'),
	(106, '106_3_Theresa_Zabell.jpg', './imagenes'),
	(106, '106_4_Theresa_Zabell.jpg', './imagenes'),
	(106, '106_5_Theresa_Zabell.jpg', './imagenes'),
	(106, '106_6_Theresa_Zabell.jpg', './imagenes'),
	(106, '106_7_Theresa_Zabell.jpg', './imagenes'),
	(107, '107_1_Tiger_Woods.jpg', './imagenes'),
	(107, '107_2_Tiger_Woods.jpg', './imagenes'),
	(107, '107_3_Tiger_Woods.jpg', './imagenes'),
	(107, '107_4_Tiger_Woods.jpg', './imagenes'),
	(107, '107_5_Tiger_Woods.jpg', './imagenes'),
	(107, '107_6_Tiger_Woods.jpg', './imagenes'),
	(108, '108_1_Tony_Hawk.jpg', './imagenes'),
	(108, '108_2_Tony_Hawk.jpg', './imagenes'),
	(108, '108_3_Tony_Hawk.jpg', './imagenes'),
	(108, '108_4_Tony_Hawk.jpg', './imagenes'),
	(108, '108_5_Tony_Hawk.jpg', './imagenes'),
	(108, '108_6_Tony_Hawk.jpg', './imagenes'),
	(109, '109_1_Usain_Bolt.jpg', './imagenes'),
	(109, '109_2_Usain_Bolt.jpg', './imagenes'),
	(109, '109_3_Usain_Bolt.jpg', './imagenes'),
	(109, '109_4_Usain_Bolt.jpg', './imagenes'),
	(109, '109_5_Usain_Bolt.jpg', './imagenes'),
	(109, '109_6_Usain_Bolt.jpg', './imagenes'),
	(109, '109_7_Usain_Bolt.jpg', './imagenes'),
	(10, '10_1_Arantxa_Sánchez_Vicario.jpg', './imagenes'),
	(10, '10_2_Arantxa_Sánchez_Vicario.jpg', './imagenes'),
	(10, '10_3_Arantxa_Sánchez_Vicario.jpg', './imagenes'),
	(10, '10_4_Arantxa_Sánchez_Vicario.jpg', './imagenes'),
	(10, '10_5_Arantxa_Sánchez_Vicario.jpg', './imagenes'),
	(110, '110_1_Valentino_Rossi.jpg', './imagenes'),
	(110, '110_2_Valentino_Rossi.jpg', './imagenes'),
	(110, '110_3_Valentino_Rossi.jpg', './imagenes'),
	(110, '110_4_Valentino_Rossi.jpg', './imagenes'),
	(110, '110_5_Valentino_Rossi.jpg', './imagenes'),
	(110, '110_6_Valentino_Rossi.jpg', './imagenes'),
	(111, '111_1_Wayne_Rainey.jpg', './imagenes'),
	(111, '111_2_Wayne_Rainey.jpg', './imagenes'),
	(111, '111_3_Wayne_Rainey.jpg', './imagenes'),
	(111, '111_4_Wayne_Rainey.jpg', './imagenes'),
	(111, '111_5_Wayne_Rainey.jpg', './imagenes'),
	(111, '111_6_Wayne_Rainey.jpg', './imagenes'),
	(111, '111_7_Wayne_Rainey.jpg', './imagenes'),
	(111, '111_8_Wayne_Rainey.jpg', './imagenes'),
	(112, '112_1_Wayne_Rooney.jpg', './imagenes'),
	(112, '112_2_Wayne_Rooney.jpg', './imagenes'),
	(112, '112_3_Wayne_Rooney.jpg', './imagenes'),
	(112, '112_4_Wayne_Rooney.jpg', './imagenes'),
	(112, '112_5_Wayne_Rooney.jpg', './imagenes'),
	(113, '113_1_Yelena_Isinbayeva.jpg', './imagenes'),
	(113, '113_2_Yelena_Isinbayeva.jpg', './imagenes'),
	(113, '113_3_Yelena_Isinbayeva.jpg', './imagenes'),
	(113, '113_4_Yelena_Isinbayeva.jpg', './imagenes'),
	(113, '113_5_Yelena_Isinbayeva.jpg', './imagenes'),
	(113, '113_6_Yelena_Isinbayeva.jpg', './imagenes'),
	(113, '113_7_Yelena_Isinbayeva.jpg', './imagenes'),
	(114, '114_1_Zinedine_Zidane.jpg', './imagenes'),
	(114, '114_2_Zinedine_Zidane.jpg', './imagenes'),
	(114, '114_3_Zinedine_Zidane.jpg', './imagenes'),
	(114, '114_4_Zinedine_Zidane.jpg', './imagenes'),
	(114, '114_5_Zinedine_Zidane.jpg', './imagenes'),
	(114, '114_6_Zinedine_Zidane.jpg', './imagenes'),
	(114, '114_7_Zinedine_Zidane.jpg', './imagenes'),
	(11, '11_1_Bjorn_Borg.jpg', './imagenes'),
	(11, '11_2_Bjorn_Borg.jpg', './imagenes'),
	(11, '11_3_Bjorn_Borg.jpg', './imagenes'),
	(11, '11_4_Bjorn_Borg.jpg', './imagenes'),
	(11, '11_5_Bjorn_Borg.jpg', './imagenes'),
	(11, '11_6_Bjorn_Borg.jpg', './imagenes'),
	(12, '12_1_Blanca_Fernández_Ochoa.jpg', './imagenes'),
	(12, '12_2_Blanca_Fernández_Ochoa.jpg', './imagenes'),
	(12, '12_3_Blanca_Fernández_Ochoa.jpg', './imagenes'),
	(12, '12_4_Blanca_Fernández_Ochoa.jpg', './imagenes'),
	(12, '12_5_Blanca_Fernández_Ochoa.jpg', './imagenes'),
	(12, '12_6_Blanca_Fernández_Ochoa.jpg', './imagenes'),
	(13, '13_1_Bob_Beamon.jpg', './imagenes'),
	(13, '13_2_Bob_Beamon.jpg', './imagenes'),
	(13, '13_3_Bob_Beamon.jpg', './imagenes'),
	(13, '13_4_Bob_Beamon.jpg', './imagenes'),
	(13, '13_5_Bob_Beamon.jpg', './imagenes'),
	(13, '13_6_Bob_Beamon.jpg', './imagenes'),
	(13, '13_7_Bob_Beamon.jpg', './imagenes'),
	(13, '13_8_Bob_Beamon.jpg', './imagenes'),
	(14, '14_1_Bobby_Fischer.jpg', './imagenes'),
	(14, '14_2_Bobby_Fischer.jpg', './imagenes'),
	(14, '14_3_Bobby_Fischer.jpg', './imagenes'),
	(14, '14_4_Bobby_Fischer.jpg', './imagenes'),
	(14, '14_5_Bobby_Fischer.jpg', './imagenes'),
	(14, '14_6_Bobby_Fischer.jpg', './imagenes'),
	(15, '15_1_Carl_Lewis.jpg', './imagenes'),
	(15, '15_2_Carl_Lewis.jpg', './imagenes'),
	(15, '15_3_Carl_Lewis.jpg', './imagenes'),
	(15, '15_4_Carl_Lewis.jpg', './imagenes'),
	(15, '15_5_Carl_Lewis.jpg', './imagenes'),
	(15, '15_6_Carl_Lewis.jpg', './imagenes'),
	(15, '15_7_Carl_Lewis.jpg', './imagenes'),
	(16, '16_1_Carlos_Sainz.jpg', './imagenes'),
	(16, '16_2_Carlos_Sainz.jpg', './imagenes'),
	(16, '16_3_Carlos_Sainz.jpg', './imagenes'),
	(16, '16_4_Carlos_Sainz.jpg', './imagenes'),
	(16, '16_5_Carlos_Sainz.jpg', './imagenes'),
	(17, '17_1_Carmelo_Anthony.jpg', './imagenes'),
	(17, '17_2_Carmelo_Anthony.jpg', './imagenes'),
	(17, '17_3_Carmelo_Anthony.jpg', './imagenes'),
	(17, '17_4_Carmelo_Anthony.jpg', './imagenes'),
	(17, '17_5_Carmelo_Anthony.jpg', './imagenes'),
	(18, '18_1_Caroline_Wozniacki.jpg', './imagenes'),
	(18, '18_2_Caroline_Wozniacki.jpg', './imagenes'),
	(18, '18_3_Caroline_Wozniacki.jpg', './imagenes'),
	(18, '18_4_Caroline_Wozniacki.jpg', './imagenes'),
	(18, '18_5_Caroline_Wozniacki.jpg', './imagenes'),
	(18, '18_6_Caroline_Wozniacki.jpg', './imagenes'),
	(19, '19_1_Conchita_Martínez.jpg', './imagenes'),
	(19, '19_2_Conchita_Martínez.jpg', './imagenes'),
	(19, '19_3_Conchita_Martínez.jpg', './imagenes'),
	(19, '19_4_Conchita_Martínez.jpg', './imagenes'),
	(19, '19_5_Conchita_Martínez.jpg', './imagenes'),
	(19, '19_6_Conchita_Martínez.jpg', './imagenes'),
	(19, '19_7_Conchita_Martínez.jpg', './imagenes'),
	(1, '1_1_Alex_Criville.jpg', './imagenes'),
	(1, '1_2_Alex_Criville.jpg', './imagenes'),
	(1, '1_3_Alex_Criville.jpg', './imagenes'),
	(1, '1_4_Alex_Criville.jpg', './imagenes'),
	(1, '1_5_Alex_Criville.jpg', './imagenes'),
	(20, '20_1_Coral_Bistuer.jpg', './imagenes'),
	(20, '20_2_Coral_Bistuer.jpg', './imagenes'),
	(20, '20_3_Coral_Bistuer.jpg', './imagenes'),
	(20, '20_4_Coral_Bistuer.jpg', './imagenes'),
	(20, '20_5_Coral_Bistuer.jpg', './imagenes'),
	(20, '20_6_Coral_Bistuer.jpg', './imagenes'),
	(20, '20_7_Coral_Bistuer.jpg', './imagenes'),
	(21, '21_1_Cristiano_Ronaldo.jpg', './imagenes'),
	(21, '21_2_Cristiano_Ronaldo.jpg', './imagenes'),
	(21, '21_3_Cristiano_Ronaldo.jpg', './imagenes'),
	(21, '21_4_Cristiano_Ronaldo.jpg', './imagenes'),
	(21, '21_5_Cristiano_Ronaldo.jpg', './imagenes'),
	(21, '21_6_Cristiano_Ronaldo.jpg', './imagenes'),
	(22, '22_1_Dani_Pedrosa.jpg', './imagenes'),
	(22, '22_2_Dani_Pedrosa.jpg', './imagenes'),
	(22, '22_3_Dani_Pedrosa.jpg', './imagenes'),
	(22, '22_4_Dani_Pedrosa.jpg', './imagenes'),
	(22, '22_5_Dani_Pedrosa.jpg', './imagenes'),
	(22, '22_6_Dani_Pedrosa.jpg', './imagenes'),
	(23, '23_1_Danica_Patrick.jpg', './imagenes'),
	(23, '23_2_Danica_Patrick.jpg', './imagenes'),
	(23, '23_3_Danica_Patrick.jpg', './imagenes'),
	(23, '23_4_Danica_Patrick.jpg', './imagenes'),
	(23, '23_5_Danica_Patrick.jpg', './imagenes'),
	(24, '24_1_Dirk_Nowitzki.jpg', './imagenes'),
	(24, '24_2_Dirk_Nowitzki.jpg', './imagenes'),
	(24, '24_3_Dirk_Nowitzki.jpg', './imagenes'),
	(24, '24_4_Dirk_Nowitzki.jpg', './imagenes'),
	(24, '24_5_Dirk_Nowitzki.jpg', './imagenes'),
	(24, '24_6_Dirk_Nowitzki.jpg', './imagenes'),
	(25, '25_1_Dwyane_Wade.jpg', './imagenes'),
	(25, '25_2_Dwyane_Wade.jpg', './imagenes'),
	(25, '25_3_Dwyane_Wade.jpg', './imagenes'),
	(25, '25_4_Dwyane_Wade.jpg', './imagenes'),
	(25, '25_5_Dwyane_Wade.jpg', './imagenes'),
	(25, '25_6_Dwyane_Wade.jpg', './imagenes'),
	(26, '26_1_Eddy_Merckx.jpg', './imagenes'),
	(26, '26_2_Eddy_Merckx.jpg', './imagenes'),
	(26, '26_3_Eddy_Merckx.jpg', './imagenes'),
	(26, '26_4_Eddy_Merckx.jpg', './imagenes'),
	(26, '26_5_Eddy_Merckx.jpg', './imagenes'),
	(26, '26_6_Eddy_Merckx.jpg', './imagenes'),
	(26, '26_7_Eddy_Merckx.jpg', './imagenes'),
	(26, '26_8_Eddy_Merckx.jpg', './imagenes'),
	(27, '27_1_Edurne_Pasaban.jpg', './imagenes'),
	(27, '27_2_Edurne_Pasaban.jpg', './imagenes'),
	(27, '27_3_Edurne_Pasaban.jpg', './imagenes'),
	(27, '27_4_Edurne_Pasaban.jpg', './imagenes'),
	(27, '27_5_Edurne_Pasaban.jpg', './imagenes'),
	(27, '27_6_Edurne_Pasaban.jpg', './imagenes'),
	(28, '28_1_Emil_Zatopek.jpg', './imagenes'),
	(28, '28_2_Emil_Zatopek.jpg', './imagenes'),
	(28, '28_3_Emil_Zatopek.jpg', './imagenes'),
	(28, '28_4_Emil_Zatopek.jpg', './imagenes'),
	(28, '28_5_Emil_Zatopek.jpg', './imagenes'),
	(28, '28_6_Emil_Zatopek.jpg', './imagenes'),
	(29, '29_1_Emilio_Butrageño.jpg', './imagenes'),
	(29, '29_2_Emilio_Butrageño.jpg', './imagenes'),
	(29, '29_3_Emilio_Butrageño.jpg', './imagenes'),
	(29, '29_4_Emilio_Butrageño.jpg', './imagenes'),
	(29, '29_5_Emilio_Butrageño.jpg', './imagenes'),
	(29, '29_6_Emilio_Butrageño.jpg', './imagenes'),
	(29, '29_7_Emilio_Butrageño.jpg', './imagenes'),
	(2, '2_1_Alexander_Popov.jpg', './imagenes'),
	(2, '2_2_Alexander_Popov.jpg', './imagenes'),
	(2, '2_3_Alexander_Popov.jpg', './imagenes'),
	(2, '2_4_Alexander_Popov.jpg', './imagenes'),
	(2, '2_5_Alexander_Popov.jpg', './imagenes'),
	(2, '2_6_Alexander_Popov.jpg', './imagenes'),
	(30, '30_1_Epi.jpg', './imagenes'),
	(30, '30_2_Epi.jpg', './imagenes'),
	(30, '30_3_Epi.jpg', './imagenes'),
	(30, '30_4_Epi.jpg', './imagenes'),
	(30, '30_5_Epi.jpg', './imagenes'),
	(31, '31_1_Evander_Holyfield.jpg', './imagenes'),
	(31, '31_2_Evander_Holyfield.jpg', './imagenes'),
	(31, '31_3_Evander_Holyfield.jpg', './imagenes'),
	(31, '31_4_Evander_Holyfield.jpg', './imagenes'),
	(31, '31_5_Evander_Holyfield.jpg', './imagenes'),
	(31, '31_6_Evander_Holyfield.jpg', './imagenes'),
	(31, '31_7_Evander_Holyfield.jpg', './imagenes'),
	(31, '31_8_Evander_Holyfield.jpg', './imagenes'),
	(32, '32_1_Fernado_Alonso.jpg', './imagenes'),
	(32, '32_2_Fernado_Alonso.jpg', './imagenes'),
	(32, '32_3_Fernado_Alonso.jpg', './imagenes'),
	(32, '32_4_Fernado_Alonso.jpg', './imagenes'),
	(32, '32_5_Fernado_Alonso.jpg', './imagenes'),
	(32, '32_6_Fernado_Alonso.jpg', './imagenes'),
	(33, '33_1_Fernando_Romay.jpg', './imagenes'),
	(33, '33_2_Fernando_Romay.jpg', './imagenes'),
	(33, '33_3_Fernando_Romay.jpg', './imagenes'),
	(33, '33_4_Fernando_Romay.jpg', './imagenes'),
	(33, '33_5_Fernando_Romay.jpg', './imagenes'),
	(33, '33_6_Fernando_Romay.jpg', './imagenes'),
	(33, '33_7_Fernando_Romay.jpg', './imagenes'),
	(34, '34_1_Fernando_Torres.jpg', './imagenes'),
	(34, '34_2_Fernando_Torres.jpg', './imagenes'),
	(34, '34_3_Fernando_Torres.jpg', './imagenes'),
	(34, '34_4_Fernando_Torres.jpg', './imagenes'),
	(34, '34_5_Fernando_Torres.jpg', './imagenes'),
	(34, '34_6_Fernando_Torres.jpg', './imagenes'),
	(34, '34_7_Fernando_Torres.jpg', './imagenes'),
	(35, '35_1_Florence_Griffith.jpg', './imagenes'),
	(35, '35_2_Florence_Griffith.jpg', './imagenes'),
	(35, '35_3_Florence_Griffith.jpg', './imagenes'),
	(35, '35_4_Florence_Griffith.jpg', './imagenes'),
	(35, '35_5_Florence_Griffith.jpg', './imagenes'),
	(35, '35_6_Florence_Griffith.jpg', './imagenes'),
	(35, '35_7_Florence_Griffith.jpg', './imagenes'),
	(35, '35_8_Florence_Griffith.jpg', './imagenes'),
	(35, '35_9_Florence_Griffith.jpg', './imagenes'),
	(36, '36_1_Floyd_Mayweather.jpg', './imagenes'),
	(36, '36_2_Floyd_Mayweather.jpg', './imagenes'),
	(36, '36_3_Floyd_Mayweather.jpg', './imagenes'),
	(36, '36_4_Floyd_Mayweather.jpg', './imagenes'),
	(36, '36_5_Floyd_Mayweather.jpg', './imagenes'),
	(36, '36_6_Floyd_Mayweather.jpg', './imagenes'),
	(36, '36_7_Floyd_Mayweather.jpg', './imagenes'),
	(37, '37_1_Franz_Beckenbauer.jpg', './imagenes'),
	(37, '37_2_Franz_Beckenbauer.jpg', './imagenes'),
	(37, '37_3_Franz_Beckenbauer.jpg', './imagenes'),
	(37, '37_4_Franz_Beckenbauer.jpg', './imagenes'),
	(37, '37_5_Franz_Beckenbauer.jpg', './imagenes'),
	(37, '37_6_Franz_Beckenbauer.jpg', './imagenes'),
	(37, '37_7_Franz_Beckenbauer.jpg', './imagenes'),
	(38, '38_1_Garrincha.jpg', './imagenes'),
	(38, '38_2_Garrincha.jpg', './imagenes'),
	(38, '38_3_Garrincha.jpg', './imagenes'),
	(38, '38_4_Garrincha.jpg', './imagenes'),
	(38, '38_5_Garrincha.jpg', './imagenes'),
	(38, '38_6_Garrincha.jpg', './imagenes'),
	(38, '38_7_Garrincha.jpg', './imagenes'),
	(39, '39_1_Gary_Kasparov.jpg', './imagenes'),
	(39, '39_2_Gary_Kasparov.jpg', './imagenes'),
	(39, '39_3_Gary_Kasparov.jpg', './imagenes'),
	(39, '39_4_Gary_Kasparov.jpg', './imagenes'),
	(39, '39_5_Gary_Kasparov.jpg', './imagenes'),
	(39, '39_6_Gary_Kasparov.jpg', './imagenes'),
	(39, '39_7_Gary_Kasparov.jpg', './imagenes'),
	(39, '39_8_Gary_Kasparov.jpg', './imagenes'),
	(3, '3_1_Alfredo_Di_Stefano.jpg', './imagenes'),
	(3, '3_2_Alfredo_Di_Stefano.jpg', './imagenes'),
	(3, '3_3_Alfredo_Di_Stefano.jpg', './imagenes'),
	(3, '3_4_Alfredo_Di_Stefano.jpg', './imagenes'),
	(3, '3_5_Alfredo_Di_Stefano.jpg', './imagenes'),
	(40, '40_1_Gemma_Mengual.jpg', './imagenes'),
	(40, '40_2_Gemma_Mengual.jpg', './imagenes'),
	(40, '40_3_Gemma_Mengual.jpg', './imagenes'),
	(40, '40_4_Gemma_Mengual.jpg', './imagenes'),
	(40, '40_5_Gemma_Mengual.jpg', './imagenes'),
	(40, '40_6_Gemma_Mengual.jpg', './imagenes'),
	(40, '40_7_Gemma_Mengual.jpg', './imagenes'),
	(41, '41_1_George_Forerman.jpg', './imagenes'),
	(41, '41_2_George_Forerman.jpg', './imagenes'),
	(41, '41_3_George_Forerman.jpg', './imagenes'),
	(41, '41_4_George_Forerman.jpg', './imagenes'),
	(41, '41_5_George_Forerman.jpg', './imagenes'),
	(41, '41_6_George_Forerman.jpg', './imagenes'),
	(41, '41_7_George_Forerman.jpg', './imagenes'),
	(42, '42_1_Giacomo_Agostini.jpg', './imagenes'),
	(42, '42_2_Giacomo_Agostini.jpg', './imagenes'),
	(42, '42_3_Giacomo_Agostini.jpg', './imagenes'),
	(42, '42_4_Giacomo_Agostini.jpg', './imagenes'),
	(42, '42_5_Giacomo_Agostini.jpg', './imagenes'),
	(42, '42_6_Giacomo_Agostini.jpg', './imagenes'),
	(42, '42_7_Giacomo_Agostini.jpg', './imagenes'),
	(43, '43_1_Gisela_Pulido.jpg', './imagenes'),
	(43, '43_2_Gisela_Pulido.jpg', './imagenes'),
	(43, '43_3_Gisela_Pulido.jpg', './imagenes'),
	(43, '43_4_Gisela_Pulido.jpg', './imagenes'),
	(43, '43_5_Gisela_Pulido.jpg', './imagenes'),
	(43, '43_6_Gisela_Pulido.jpg', './imagenes'),
	(44, '44_1_Ian_Thorpe.jpg', './imagenes'),
	(44, '44_2_Ian_Thorpe.jpg', './imagenes'),
	(44, '44_3_Ian_Thorpe.jpg', './imagenes'),
	(44, '44_4_Ian_Thorpe.jpg', './imagenes'),
	(44, '44_5_Ian_Thorpe.jpg', './imagenes'),
	(44, '44_6_Ian_Thorpe.jpg', './imagenes'),
	(45, '45_1_Javier_Sotomayor.jpg', './imagenes'),
	(45, '45_2_Javier_Sotomayor.jpg', './imagenes'),
	(45, '45_3_Javier_Sotomayor.jpg', './imagenes'),
	(45, '45_4_Javier_Sotomayor.jpg', './imagenes'),
	(45, '45_5_Javier_Sotomayor.jpg', './imagenes'),
	(45, '45_6_Javier_Sotomayor.jpg', './imagenes'),
	(46, '46_1_Jenson_Button.jpg', './imagenes'),
	(46, '46_2_Jenson_Button.jpg', './imagenes'),
	(46, '46_3_Jenson_Button.jpg', './imagenes'),
	(46, '46_4_Jenson_Button.jpg', './imagenes'),
	(46, '46_5_Jenson_Button.jpg', './imagenes'),
	(47, '47_1_Jesse_Owens.jpg', './imagenes'),
	(47, '47_2_Jesse_Owens.jpg', './imagenes'),
	(47, '47_3_Jesse_Owens.jpg', './imagenes'),
	(47, '47_4_Jesse_Owens.jpg', './imagenes'),
	(47, '47_5_Jesse_Owens.jpg', './imagenes'),
	(47, '47_6_Jesse_Owens.jpg', './imagenes'),
	(47, '47_7_Jesse_Owens.jpg', './imagenes'),
	(48, '48_1_Joe_Di_Maggio.jpg', './imagenes'),
	(48, '48_2_Joe_Di_Maggio.jpg', './imagenes'),
	(48, '48_3_Joe_Di_Maggio.jpg', './imagenes'),
	(48, '48_4_Joe_Di_Maggio.jpg', './imagenes'),
	(48, '48_5_Joe_Di_Maggio.jpg', './imagenes'),
	(48, '48_6_Joe_Di_Maggio.jpg', './imagenes'),
	(49, '49_1_Joe_Frazier.jpg', './imagenes'),
	(49, '49_2_Joe_Frazier.jpg', './imagenes'),
	(49, '49_3_Joe_Frazier.jpg', './imagenes'),
	(49, '49_4_Joe_Frazier.jpg', './imagenes'),
	(49, '49_5_Joe_Frazier.jpg', './imagenes'),
	(49, '49_6_Joe_Frazier.jpg', './imagenes'),
	(4, '4_1_Almudena_Cid.jpg', './imagenes'),
	(4, '4_2_Almudena_Cid.jpg', './imagenes'),
	(4, '4_3_Almudena_Cid.jpg', './imagenes'),
	(4, '4_4_Almudena_Cid.jpg', './imagenes'),
	(4, '4_5_Almudena_Cid.jpg', './imagenes'),
	(4, '4_6_Almudena_Cid.jpg', './imagenes'),
	(4, '4_7_Almudena_Cid.jpg', './imagenes'),
	(50, '50_1_Joe_Montana.jpg', './imagenes'),
	(50, '50_2_Joe_Montana.jpg', './imagenes'),
	(50, '50_3_Joe_Montana.jpg', './imagenes'),
	(50, '50_4_Joe_Montana.jpg', './imagenes'),
	(50, '50_5_Joe_Montana.jpg', './imagenes'),
	(50, '50_6_Joe_Montana.jpg', './imagenes'),
	(50, '50_7_Joe_Montana.jpg', './imagenes'),
	(51, '51_1_Johan_Cruyff.jpg', './imagenes'),
	(51, '51_2_Johan_Cruyff.jpg', './imagenes'),
	(51, '51_3_Johan_Cruyff.jpg', './imagenes'),
	(51, '51_4_Johan_Cruyff.jpg', './imagenes'),
	(51, '51_5_Johan_Cruyff.jpg', './imagenes'),
	(51, '51_6_Johan_Cruyff.jpg', './imagenes'),
	(51, '51_7_Johan_Cruyff.jpg', './imagenes'),
	(52, '52_1_Jorge_Lorenzo.jpg', './imagenes'),
	(52, '52_2_Jorge_Lorenzo.jpg', './imagenes'),
	(52, '52_3_Jorge_Lorenzo.jpg', './imagenes'),
	(52, '52_4_Jorge_Lorenzo.jpg', './imagenes'),
	(52, '52_5_Jorge_Lorenzo.jpg', './imagenes'),
	(52, '52_6_Jorge_Lorenzo.jpg', './imagenes'),
	(53, '53_1_Jose_Raul_Capablanca.jpg', './imagenes'),
	(53, '53_2_Jose_Raul_Capablanca.jpg', './imagenes'),
	(53, '53_3_Jose_Raul_Capablanca.jpg', './imagenes'),
	(53, '53_4_Jose_Raul_Capablanca.jpg', './imagenes'),
	(53, '53_5_Jose_Raul_Capablanca.jpg', './imagenes'),
	(53, '53_6_Jose_Raul_Capablanca.jpg', './imagenes'),
	(53, '53_7_Jose_Raul_Capablanca.jpg', './imagenes'),
	(54, '54_1_Juan_Carlos_Navarro.jpg', './imagenes'),
	(54, '54_2_Juan_Carlos_Navarro.jpg', './imagenes'),
	(54, '54_3_Juan_Carlos_Navarro.jpg', './imagenes'),
	(54, '54_4_Juan_Carlos_Navarro.jpg', './imagenes'),
	(54, '54_5_Juan_Carlos_Navarro.jpg', './imagenes'),
	(55, '55_1_Juan_Manuel_Fangio.jpg', './imagenes'),
	(55, '55_2_Juan_Manuel_Fangio.jpg', './imagenes'),
	(55, '55_3_Juan_Manuel_Fangio.jpg', './imagenes'),
	(55, '55_4_Juan_Manuel_Fangio.jpg', './imagenes'),
	(55, '55_5_Juan_Manuel_Fangio.jpg', './imagenes'),
	(56, '56_1_Jutta_Kleinsmith.jpg', './imagenes'),
	(56, '56_2_Jutta_Kleinsmith.jpg', './imagenes'),
	(56, '56_3_Jutta_Kleinsmith.jpg', './imagenes'),
	(56, '56_4_Jutta_Kleinsmith.jpg', './imagenes'),
	(56, '56_5_Jutta_Kleinsmith.jpg', './imagenes'),
	(56, '56_6_Jutta_Kleinsmith.jpg', './imagenes'),
	(57, '57_1_Kareem_Abdul_Jabbar.jpg', './imagenes'),
	(57, '57_2_Kareem_Abdul_Jabbar.jpg', './imagenes'),
	(57, '57_3_Kareem_Abdul_Jabbar.jpg', './imagenes'),
	(57, '57_4_Kareem_Abdul_Jabbar.jpg', './imagenes'),
	(57, '57_5_Kareem_Abdul_Jabbar.jpg', './imagenes'),
	(57, '57_6_Kareem_Abdul_Jabbar.jpg', './imagenes'),
	(57, '57_7_Kareem_Abdul_Jabbar.jpg', './imagenes'),
	(58, '58_1_Karl_Malone.jpg', './imagenes'),
	(58, '58_2_Karl_Malone.jpg', './imagenes'),
	(58, '58_3_Karl_Malone.jpg', './imagenes'),
	(58, '58_4_Karl_Malone.jpg', './imagenes'),
	(58, '58_5_Karl_Malone.jpg', './imagenes'),
	(58, '58_6_Karl_Malone.jpg', './imagenes'),
	(58, '58_7_Karl_Malone.jpg', './imagenes'),
	(59, '59_1_Kobe_Bryant.jpg', './imagenes'),
	(59, '59_2_Kobe_Bryant.jpg', './imagenes'),
	(59, '59_3_Kobe_Bryant.jpg', './imagenes'),
	(59, '59_4_Kobe_Bryant.jpg', './imagenes'),
	(59, '59_5_Kobe_Bryant.jpg', './imagenes'),
	(59, '59_6_Kobe_Bryant.jpg', './imagenes'),
	(5, '5_1_Amaya_Valdemoro.jpg', './imagenes'),
	(5, '5_2_Amaya_Valdemoro.jpg', './imagenes'),
	(5, '5_3_Amaya_Valdemoro.jpg', './imagenes'),
	(5, '5_4_Amaya_Valdemoro.jpg', './imagenes'),
	(5, '5_5_Amaya_Valdemoro.jpg', './imagenes'),
	(5, '5_6_Amaya_Valdemoro.jpg', './imagenes'),
	(60, '60_1_Lance_Armstrong.jpg', './imagenes'),
	(60, '60_2_Lance_Armstrong.jpg', './imagenes'),
	(60, '60_3_Lance_Armstrong.jpg', './imagenes'),
	(60, '60_4_Lance_Armstrong.jpg', './imagenes'),
	(60, '60_5_Lance_Armstrong.jpg', './imagenes'),
	(61, '61_1_Larry_Bird.jpg', './imagenes'),
	(61, '61_2_Larry_Bird.jpg', './imagenes'),
	(61, '61_3_Larry_Bird.jpg', './imagenes'),
	(61, '61_4_Larry_Bird.jpg', './imagenes'),
	(61, '61_5_Larry_Bird.jpg', './imagenes'),
	(61, '61_6_Larry_Bird.jpg', './imagenes'),
	(61, '61_7_Larry_Bird.jpg', './imagenes'),
	(61, '61_8_Larry_Bird.jpg', './imagenes'),
	(62, '62_1_Lebron_James.jpg', './imagenes'),
	(62, '62_2_Lebron_James.jpg', './imagenes'),
	(62, '62_3_Lebron_James.jpg', './imagenes'),
	(62, '62_4_Lebron_James.jpg', './imagenes'),
	(62, '62_5_Lebron_James.jpg', './imagenes'),
	(62, '62_6_Lebron_James.jpg', './imagenes'),
	(63, '63_1_Lev_Yashin.jpg', './imagenes'),
	(63, '63_2_Lev_Yashin.jpg', './imagenes'),
	(63, '63_3_Lev_Yashin.jpg', './imagenes'),
	(63, '63_4_Lev_Yashin.jpg', './imagenes'),
	(63, '63_5_Lev_Yashin.jpg', './imagenes'),
	(63, '63_6_Lev_Yashin.jpg', './imagenes'),
	(63, '63_7_Lev_Yashin.jpg', './imagenes'),
	(63, '63_8_Lev_Yashin.jpg', './imagenes'),
	(64, '64_1_Lionel_Messi.jpg', './imagenes'),
	(64, '64_2_Lionel_Messi.jpg', './imagenes'),
	(64, '64_3_Lionel_Messi.jpg', './imagenes'),
	(64, '64_4_Lionel_Messi.jpg', './imagenes'),
	(64, '64_5_Lionel_Messi.jpg', './imagenes'),
	(64, '64_6_Lionel_Messi.jpg', './imagenes'),
	(65, '65_1_Lothar_Matthaus.jpg', './imagenes'),
	(65, '65_2_Lothar_Matthaus.jpg', './imagenes'),
	(65, '65_3_Lothar_Matthaus.jpg', './imagenes'),
	(65, '65_4_Lothar_Matthaus.jpg', './imagenes'),
	(65, '65_5_Lothar_Matthaus.jpg', './imagenes'),
	(65, '65_6_Lothar_Matthaus.jpg', './imagenes'),
	(65, '65_7_Lothar_Matthaus.jpg', './imagenes'),
	(66, '66_1_Magic_Johnson.jpg', './imagenes'),
	(66, '66_2_Magic_Johnson.jpg', './imagenes'),
	(66, '66_3_Magic_Johnson.jpg', './imagenes'),
	(66, '66_4_Magic_Johnson.jpg', './imagenes'),
	(66, '66_5_Magic_Johnson.jpg', './imagenes'),
	(66, '66_6_Magic_Johnson.jpg', './imagenes'),
	(66, '66_7_Magic_Johnson.jpg', './imagenes'),
	(67, '67_1_Manny_Pacquiao.jpg', './imagenes'),
	(67, '67_2_Manny_Pacquiao.jpg', './imagenes'),
	(67, '67_3_Manny_Pacquiao.jpg', './imagenes'),
	(67, '67_4_Manny_Pacquiao.jpg', './imagenes'),
	(67, '67_5_Manny_Pacquiao.jpg', './imagenes'),
	(68, '68_1_María_De_Villota.jpg', './imagenes'),
	(68, '68_2_María_De_Villota.jpg', './imagenes'),
	(68, '68_3_María_De_Villota.jpg', './imagenes'),
	(68, '68_4_María_De_Villota.jpg', './imagenes'),
	(68, '68_5_María_De_Villota.jpg', './imagenes'),
	(69, '69_1_Maradona.jpg', './imagenes'),
	(69, '69_2_Maradona.jpg', './imagenes'),
	(69, '69_3_Maradona.jpg', './imagenes'),
	(69, '69_4_Maradona.jpg', './imagenes'),
	(69, '69_5_Maradona.jpg', './imagenes'),
	(69, '69_6_Maradona.jpg', './imagenes'),
	(69, '69_7_Maradona.jpg', './imagenes'),
	(69, '69_8_Maradona.jpg', './imagenes'),
	(6, '6_1_Ana_Ivanovic.jpg', './imagenes'),
	(6, '6_2_Ana_Ivanovic.jpg', './imagenes'),
	(6, '6_3_Ana_Ivanovic.jpg', './imagenes'),
	(6, '6_4_Ana_Ivanovic.jpg', './imagenes'),
	(6, '6_5_Ana_Ivanovic.jpg', './imagenes'),
	(6, '6_6_Ana_Ivanovic.jpg', './imagenes'),
	(70, '70_1_Marc_Marquez.jpg', './imagenes'),
	(70, '70_2_Marc_Marquez.jpg', './imagenes'),
	(70, '70_3_Marc_Marquez.jpg', './imagenes'),
	(70, '70_4_Marc_Marquez.jpg', './imagenes'),
	(70, '70_5_Marc_Marquez.jpg', './imagenes'),
	(71, '71_1_Maria_Sharapova.jpg', './imagenes'),
	(71, '71_2_Maria_Sharapova.jpg', './imagenes'),
	(71, '71_3_Maria_Sharapova.jpg', './imagenes'),
	(71, '71_4_Maria_Sharapova.jpg', './imagenes'),
	(71, '71_5_Maria_Sharapova.jpg', './imagenes'),
	(71, '71_6_Maria_Sharapova.jpg', './imagenes'),
	(71, '71_7_Maria_Sharapova.jpg', './imagenes'),
	(72, '72_1_Mark_Spitz.jpg', './imagenes'),
	(72, '72_2_Mark_Spitz.jpg', './imagenes'),
	(72, '72_3_Mark_Spitz.jpg', './imagenes'),
	(72, '72_4_Mark_Spitz.jpg', './imagenes'),
	(72, '72_5_Mark_Spitz.jpg', './imagenes'),
	(72, '72_6_Mark_Spitz.jpg', './imagenes'),
	(73, '73_1_Marta_Domínguez.jpg', './imagenes'),
	(73, '73_2_Marta_Domínguez.jpg', './imagenes'),
	(73, '73_3_Marta_Domínguez.jpg', './imagenes'),
	(73, '73_4_Marta_Domínguez.jpg', './imagenes'),
	(73, '73_5_Marta_Domínguez.jpg', './imagenes'),
	(73, '73_6_Marta_Domínguez.jpg', './imagenes'),
	(73, '73_7_Marta_Domínguez.jpg', './imagenes'),
	(74, '74_1_Michael_Johnson.jpg', './imagenes'),
	(74, '74_2_Michael_Johnson.jpg', './imagenes'),
	(74, '74_3_Michael_Johnson.jpg', './imagenes'),
	(74, '74_4_Michael_Johnson.jpg', './imagenes'),
	(74, '74_5_Michael_Johnson.jpg', './imagenes'),
	(74, '74_6_Michael_Johnson.jpg', './imagenes'),
	(74, '74_7_Michael_Johnson.jpg', './imagenes'),
	(74, '74_8_Michael_Johnson.jpg', './imagenes'),
	(74, '74_9_Michael_Johnson.jpg', './imagenes'),
	(75, '75_1_Michael_Jordan.jpg', './imagenes'),
	(75, '75_2_Michael_Jordan.jpg', './imagenes'),
	(75, '75_3_Michael_Jordan.jpg', './imagenes'),
	(75, '75_4_Michael_Jordan.jpg', './imagenes'),
	(75, '75_5_Michael_Jordan.jpg', './imagenes'),
	(75, '75_6_Michael_Jordan.jpg', './imagenes'),
	(75, '75_7_Michael_Jordan.jpg', './imagenes'),
	(76, '76_1_Michael_Phelps.jpg', './imagenes'),
	(76, '76_2_Michael_Phelps.jpg', './imagenes'),
	(76, '76_3_Michael_Phelps.jpg', './imagenes'),
	(76, '76_4_Michael_Phelps.jpg', './imagenes'),
	(77, '77_1_Michael_Schumacher.jpg', './imagenes'),
	(77, '77_2_Michael_Schumacher.jpg', './imagenes'),
	(77, '77_3_Michael_Schumacher.jpg', './imagenes'),
	(77, '77_4_Michael_Schumacher.jpg', './imagenes'),
	(78, '78_1_Michel_Platini.jpg', './imagenes'),
	(78, '78_2_Michel_Platini.jpg', './imagenes'),
	(78, '78_3_Michel_Platini.jpg', './imagenes'),
	(78, '78_4_Michel_Platini.jpg', './imagenes'),
	(78, '78_5_Michel_Platini.jpg', './imagenes'),
	(79, '79_1_Miguel_Indurain.jpg', './imagenes'),
	(79, '79_2_Miguel_Indurain.jpg', './imagenes'),
	(79, '79_3_Miguel_Indurain.jpg', './imagenes'),
	(79, '79_4_Miguel_Indurain.jpg', './imagenes'),
	(79, '79_5_Miguel_Indurain.jpg', './imagenes'),
	(79, '79_6_Miguel_Indurain.jpg', './imagenes'),
	(79, '79_7_Miguel_Indurain.jpg', './imagenes'),
	(7, '7_1_Anatoli_Karpov.jpg', './imagenes'),
	(7, '7_2_Anatoli_Karpov.jpg', './imagenes'),
	(7, '7_3_Anatoli_Karpov.jpg', './imagenes'),
	(7, '7_4_Anatoli_Karpov.jpg', './imagenes'),
	(7, '7_5_Anatoli_Karpov.jpg', './imagenes'),
	(7, '7_6_Anatoli_Karpov.jpg', './imagenes'),
	(7, '7_7_Anatoli_Karpov.jpg', './imagenes'),
	(7, '7_8_Anatoli_Karpov.jpg', './imagenes'),
	(80, '80_1_Mike_Doohan.jpg', './imagenes'),
	(80, '80_2_Mike_Doohan.jpg', './imagenes'),
	(80, '80_3_Mike_Doohan.jpg', './imagenes'),
	(80, '80_4_Mike_Doohan.jpg', './imagenes'),
	(80, '80_5_Mike_Doohan.jpg', './imagenes'),
	(81, '81_1_Mike_Tyson.jpg', './imagenes'),
	(81, '81_2_Mike_Tyson.jpg', './imagenes'),
	(81, '81_3_Mike_Tyson.jpg', './imagenes'),
	(81, '81_4_Mike_Tyson.jpg', './imagenes'),
	(81, '81_5_Mike_Tyson.jpg', './imagenes'),
	(81, '81_6_Mike_Tyson.jpg', './imagenes'),
	(81, '81_7_Mike_Tyson.jpg', './imagenes'),
	(81, '81_8_Mike_Tyson.jpg', './imagenes'),
	(82, '82_1_Mireia_Belmonte.jpg', './imagenes'),
	(82, '82_2_Mireia_Belmonte.jpg', './imagenes'),
	(82, '82_3_Mireia_Belmonte.jpg', './imagenes'),
	(82, '82_4_Mireia_Belmonte.jpg', './imagenes'),
	(82, '82_5_Mireia_Belmonte.jpg', './imagenes'),
	(82, '82_6_Mireia_Belmonte.jpg', './imagenes'),
	(82, '82_7_Mireia_Belmonte.jpg', './imagenes'),
	(83, '83_1_Muhammad_Ali.jpg', './imagenes'),
	(83, '83_2_Muhammad_Ali.jpg', './imagenes'),
	(83, '83_3_Muhammad_Ali.jpg', './imagenes'),
	(83, '83_4_Muhammad_Ali.jpg', './imagenes'),
	(83, '83_5_Muhammad_Ali.jpg', './imagenes'),
	(83, '83_6_Muhammad_Ali.jpg', './imagenes'),
	(83, '83_7_Muhammad_Ali.jpg', './imagenes'),
	(84, '84_1_Nadia_Comaneci.jpg', './imagenes'),
	(84, '84_2_Nadia_Comaneci.jpg', './imagenes'),
	(84, '84_3_Nadia_Comaneci.jpg', './imagenes'),
	(84, '84_4_Nadia_Comaneci.jpg', './imagenes'),
	(84, '84_5_Nadia_Comaneci.jpg', './imagenes'),
	(84, '84_6_Nadia_Comaneci.jpg', './imagenes'),
	(84, '84_7_Nadia_Comaneci.jpg', './imagenes'),
	(84, '84_8_Nadia_Comaneci.jpg', './imagenes'),
	(85, '85_1_Nani_Roma.jpg', './imagenes'),
	(85, '85_2_Nani_Roma.jpg', './imagenes'),
	(85, '85_3_Nani_Roma.jpg', './imagenes'),
	(85, '85_4_Nani_Roma.jpg', './imagenes'),
	(85, '85_5_Nani_Roma.jpg', './imagenes'),
	(85, '85_6_Nani_Roma.jpg', './imagenes'),
	(86, '86_1_Nani_Roma.jpg', './imagenes'),
	(86, '86_2_Nani_Roma.jpg', './imagenes'),
	(86, '86_3_Nani_Roma.jpg', './imagenes'),
	(86, '86_4_Nani_Roma.jpg', './imagenes'),
	(86, '86_5_Nani_Roma.jpg', './imagenes'),
	(86, '86_6_Nani_Roma.jpg', './imagenes'),
	(87, '87_1_Paul_Gasol.jpg', './imagenes'),
	(87, '87_2_Paul_Gasol.jpg', './imagenes'),
	(87, '87_3_Paul_Gasol.jpg', './imagenes'),
	(87, '87_4_Paul_Gasol.jpg', './imagenes'),
	(87, '87_5_Paul_Gasol.jpg', './imagenes'),
	(87, '87_6_Paul_Gasol.jpg', './imagenes'),
	(88, '88_1_Pelé.jpg', './imagenes'),
	(88, '88_2_Pelé.jpg', './imagenes'),
	(88, '88_3_Pelé.jpg', './imagenes'),
	(88, '88_4_Pelé.jpg', './imagenes'),
	(88, '88_5_Pelé.jpg', './imagenes'),
	(88, '88_6_Pelé.jpg', './imagenes'),
	(89, '89_1_Pete_Sampras.jpg', './imagenes'),
	(89, '89_2_Pete_Sampras.jpg', './imagenes'),
	(89, '89_3_Pete_Sampras.jpg', './imagenes'),
	(89, '89_4_Pete_Sampras.jpg', './imagenes'),
	(89, '89_5_Pete_Sampras.jpg', './imagenes'),
	(89, '89_6_Pete_Sampras.jpg', './imagenes'),
	(8, '8_1_Angel_Nieto.jpg', './imagenes'),
	(8, '8_2_Angel_Nieto.jpg', './imagenes'),
	(8, '8_3_Angel_Nieto.jpg', './imagenes'),
	(8, '8_4_Angel_Nieto.jpg', './imagenes'),
	(8, '8_5_Angel_Nieto.jpg', './imagenes'),
	(8, '8_6_Angel_Nieto.jpg', './imagenes'),
	(90, '90_1_Peyton_Manning.jpg', './imagenes'),
	(90, '90_2_Peyton_Manning.jpg', './imagenes'),
	(90, '90_3_Peyton_Manning.jpg', './imagenes'),
	(90, '90_4_Peyton_Manning.jpg', './imagenes'),
	(90, '90_5_Peyton_Manning.jpg', './imagenes'),
	(91, '91_1_Rafa_Nadal.jpg', './imagenes'),
	(91, '91_2_Rafa_Nadal.jpg', './imagenes'),
	(91, '91_3_Rafa_Nadal.jpg', './imagenes'),
	(91, '91_4_Rafa_Nadal.jpg', './imagenes'),
	(91, '91_5_Rafa_Nadal.jpg', './imagenes'),
	(92, '92_1_Rocky_Marciano.jpg', './imagenes'),
	(92, '92_2_Rocky_Marciano.jpg', './imagenes'),
	(92, '92_3_Rocky_Marciano.jpg', './imagenes'),
	(92, '92_4_Rocky_Marciano.jpg', './imagenes'),
	(92, '92_5_Rocky_Marciano.jpg', './imagenes'),
	(92, '92_6_Rocky_Marciano.jpg', './imagenes'),
	(92, '92_7_Rocky_Marciano.jpg', './imagenes'),
	(92, '92_8_Rocky_Marciano.jpg', './imagenes'),
	(93, '93_1_Roger_Federer.jpg', './imagenes'),
	(93, '93_2_Roger_Federer.jpg', './imagenes'),
	(93, '93_3_Roger_Federer.jpg', './imagenes'),
	(93, '93_4_Roger_Federer.jpg', './imagenes'),
	(93, '93_5_Roger_Federer.jpg', './imagenes'),
	(94, '94_1_Ronaldinho.jpg', './imagenes'),
	(94, '94_2_Ronaldinho.jpg', './imagenes'),
	(94, '94_3_Ronaldinho.jpg', './imagenes'),
	(94, '94_4_Ronaldinho.jpg', './imagenes'),
	(94, '94_5_Ronaldinho.jpg', './imagenes'),
	(94, '94_6_Ronaldinho.jpg', './imagenes'),
	(94, '94_7_Ronaldinho.jpg', './imagenes'),
	(95, '95_1_Ronaldo.jpg', './imagenes'),
	(95, '95_2_Ronaldo.jpg', './imagenes'),
	(95, '95_3_Ronaldo.jpg', './imagenes'),
	(95, '95_4_Ronaldo.jpg', './imagenes'),
	(95, '95_5_Ronaldo.jpg', './imagenes'),
	(95, '95_6_Ronaldo.jpg', './imagenes'),
	(96, '96_1_Scottie_Pippen.jpg', './imagenes'),
	(96, '96_2_Scottie_Pippen.jpg', './imagenes'),
	(96, '96_3_Scottie_Pippen.jpg', './imagenes'),
	(96, '96_4_Scottie_Pippen.jpg', './imagenes'),
	(96, '96_5_Scottie_Pippen.jpg', './imagenes'),
	(96, '96_6_Scottie_Pippen.jpg', './imagenes'),
	(97, '97_1_Sebastien_Loeb.jpg', './imagenes'),
	(97, '97_2_Sebastien_Loeb.jpg', './imagenes'),
	(97, '97_3_Sebastien_Loeb.jpg', './imagenes'),
	(97, '97_4_Sebastien_Loeb.jpg', './imagenes'),
	(97, '97_5_Sebastien_Loeb.jpg', './imagenes'),
	(98, '98_1_Serena_Williams.jpg', './imagenes'),
	(98, '98_2_Serena_Williams.jpg', './imagenes'),
	(98, '98_3_Serena_Williams.jpg', './imagenes'),
	(98, '98_4_Serena_Williams.jpg', './imagenes'),
	(98, '98_5_Serena_Williams.jpg', './imagenes'),
	(98, '98_6_Serena_Williams.jpg', './imagenes'),
	(98, '98_7_Serena_Williams.jpg', './imagenes'),
	(99, '99_1_Sergei_Bubka.jpg', './imagenes'),
	(99, '99_2_Sergei_Bubka.jpg', './imagenes'),
	(99, '99_3_Sergei_Bubka.jpg', './imagenes'),
	(99, '99_4_Sergei_Bubka.jpg', './imagenes'),
	(99, '99_5_Sergei_Bubka.jpg', './imagenes'),
	(99, '99_6_Sergei_Bubka.jpg', './imagenes'),
	(99, '99_7_Sergei_Bubka.jpg', './imagenes'),
	(9, '9_1_Anna_Kournikova.jpg', './imagenes'),
	(9, '9_2_Anna_Kournikova.jpg', './imagenes'),
	(9, '9_3_Anna_Kournikova.jpg', './imagenes'),
	(9, '9_4_Anna_Kournikova.jpg', './imagenes'),
	(9, '9_5_Anna_Kournikova.jpg', './imagenes'),
	(9, '9_6_Anna_Kournikova.jpg', './imagenes'),
	(9, '9_7_Anna_Kournikova.jpg', './imagenes'),
	(9, '9_8_Anna_Kournikova.jpg', './');
